### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [msarit/splurtyarit#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by msarit** [comment]
Hi Ken! So I added the following to my `<head>:`
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

But when I resize my browser, I don't really see the difference it makes... what am I missing please? :)

(glad you liked the emoticon lol)

**Comment by kenmazaika** [comment]
Awesome!  That's the right HTML tag, and it does belong in the `head`.  It only will make a difference on actual mobile devices (not browser windows that are small).  If you visit your application on heroku before and after the change, you should see the value if you're using an actual mobile device (iPhone, Android, etc.).

Hope this helps!

**Comment by msarit** [comment]
that helps a lot! Thanks again Ken. Loving the course so far! 😄
